# Codacy Configuration
# Exclude paths that generate false positives or noise
# Last updated: 2025-12-20 - Optimized for solo developer workflow

---
exclude_paths:
  # Documentation files (no code quality impact)
  - "**/*.md"
  - "docs/**"
  - "outputs/**"

  # SQL Migrations - Supabase uses Postgres, not SQL Server (T-SQL)
  # Rules like SET NOCOUNT ON, SET ANSI_NULLS are T-SQL specific
  - "supabase/migrations/**"

  # Test artifacts and scripts
  - "test-artifacts/**"
  - "scripts/audit_phase2/**"
  - "scripts/smoke-tests_archive/**"

  # SQL fix scripts (one-time use)
  - "*.sql"
  - "fix_*.sql"
  - "audit_*.sql"

  # Privacy components - intentional DOM manipulation patterns
  - "src/hooks/useClarity.ts"

# ===========================================
# ENGINES - Disable overly strict minor rules
# ===========================================
engines:
  eslint:
    enabled: true
    # Allow React patterns that trigger false positives
    exclude_patterns:
      - "src/components/privacy/**"
      - "src/components/tours/**"
      - "src/hooks/use*.ts"


