-- SCOLARITÉ (8) + VACANCES (6) = 14 dernières activités
INSERT INTO public.activities (structure_id, title, category, description, images, age_min, age_max, tags, price_base, price_note, accepts_aid_types, payment_echelonned, covoiturage_enabled, accessibility_checklist, capacity_policy, published)
VALUES
  -- SCOLARITÉ (27-34)
  ((SELECT id FROM structures WHERE name = 'Bibliothèque Municipale Tarentaize'), 'Aide aux Devoirs', 'Scolarité', 'Soutien scolaire toutes matières. Aide méthodologie, encadrement devoirs.', ARRAY['https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=800'], 6, 15, ARRAY['soutien', 'devoirs', 'école'], 0, 'Gratuit', '[]'::jsonb, false, false, jsonb_build_object('pmr_access', true, 'sensory_friendly', true), jsonb_build_object('seats_total', 30, 'seats_remaining', 15, 'waitlist_enabled', false), true),
  ((SELECT id FROM structures WHERE name = 'Bibliothèque Municipale Tarentaize'), 'Anglais Kids', 'Scolarité', 'Anglais ludique enfants. Jeux, chansons, conversations simples.', ARRAY['https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=800'], 6, 12, ARRAY['anglais', 'langues', 'éducation'], 100, '', '["CAF"]'::jsonb, true, false, jsonb_build_object('pmr_access', true), jsonb_build_object('seats_total', 15, 'seats_remaining', 7, 'waitlist_enabled', true), true),
  ((SELECT id FROM structures WHERE name = 'École des Beaux-Arts'), 'Histoire de l''Art Junior', 'Scolarité', 'Découverte grands artistes, mouvements artistiques. Visites musées.', ARRAY['https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?w=800'], 10, 17, ARRAY['art', 'histoire', 'culture'], 80, '', '["CAF"]'::jsonb, false, false, jsonb_build_object('pmr_access', true), jsonb_build_object('seats_total', 18, 'seats_remaining', 10, 'waitlist_enabled', false), true),
  ((SELECT id FROM structures WHERE name = 'La Rotonde - Espace Sciences'), 'Maths Ludiques', 'Scolarité', 'Mathématiques par le jeu. Énigmes, défis logique, magie mathématique.', ARRAY['https://images.unsplash.com/photo-1509228468518-180dd4864904?w=800'], 8, 14, ARRAY['maths', 'logique', 'STEM'], 60, '', '["CAF"]'::jsonb, false, false, jsonb_build_object('pmr_access', true), jsonb_build_object('seats_total', 16, 'seats_remaining', 9, 'waitlist_enabled', false), true),
  ((SELECT id FROM structures WHERE name = 'Bibliothèque Municipale Tarentaize'), 'Club Lecture Jeunes', 'Scolarité', 'Découverte littérature jeunesse. Débats livres, rencontres auteurs.', ARRAY['https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=800'], 9, 16, ARRAY['lecture', 'livres', 'littérature'], 0, 'Gratuit', '[]'::jsonb, false, false, jsonb_build_object('pmr_access', true, 'sensory_friendly', true), jsonb_build_object('seats_total', 20, 'seats_remaining', 12, 'waitlist_enabled', false), true),
  ((SELECT id FROM structures WHERE name = 'La Rotonde - Espace Sciences'), 'Initiation Astronomie', 'Scolarité', 'Découverte système solaire, constellations. Observation télescope.', ARRAY['https://images.unsplash.com/photo-1462331940025-496dfbfc7564?w=800'], 8, 15, ARRAY['astronomie', 'sciences', 'espace'], 70, '', '["CAF"]'::jsonb, false, true, jsonb_build_object('pmr_access', true), jsonb_build_object('seats_total', 12, 'seats_remaining', 5, 'waitlist_enabled', true), true),
  ((SELECT id FROM structures WHERE name = 'École des Beaux-Arts'), 'Écriture Créative', 'Scolarité', 'Atelier écriture textes courts, poésie, nouvelles. Expression personnelle.', ARRAY['https://images.unsplash.com/photo-1455390582262-044cdead277a?w=800'], 11, 17, ARRAY['écriture', 'littérature', 'créativité'], 50, '', '["CAF"]'::jsonb, false, false, jsonb_build_object('pmr_access', true), jsonb_build_object('seats_total', 14, 'seats_remaining', 8, 'waitlist_enabled', false), true),
  ((SELECT id FROM structures WHERE name = 'Bibliothèque Municipale Tarentaize'), 'Préparation Brevet', 'Scolarité', 'Stage intensif révisions Brevet. Méthodologie examens, annales.', ARRAY['https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=800'], 14, 16, ARRAY['brevet', 'révisions', 'examens'], 120, 'Stage 1 semaine vacances', '["CAF", "PassSport"]'::jsonb, true, false, jsonb_build_object('pmr_access', true), jsonb_build_object('seats_total', 20, 'seats_remaining', 11, 'waitlist_enabled', true), true),
  
  -- VACANCES (35-40)
  ((SELECT id FROM structures WHERE name = 'Colonie Le Grand Air - Pilat'), 'Colonie Montagne Hiver', 'Vacances', 'Séjour montagne Pilat: ski, raquettes, veillées. 5 jours pension complète.', ARRAY['https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=800'], 8, 16, ARRAY['colonie', 'montagne', 'ski', 'hiver'], 350, '5 jours pension complète', '["CAF", "PassSport"]'::jsonb, true, true, jsonb_build_object('pmr_access', false, 'specialized_staff', true), jsonb_build_object('seats_total', 24, 'seats_remaining', 10, 'waitlist_enabled', true), true),
  ((SELECT id FROM structures WHERE name = 'Base de Loisirs du Barrage de Grangent'), 'Stage Voile Été', 'Vacances', 'Initiation voile Optimist sur lac Grangent. Stage 1 semaine avec diplôme.', ARRAY['https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800'], 9, 16, ARRAY['voile', 'nautique', 'lac', 'été'], 280, 'Gilet sauvetage fourni', '["CAF", "PassSport"]'::jsonb, true, true, jsonb_build_object('pmr_access', true, 'adapted_equipment', true), jsonb_build_object('seats_total', 16, 'seats_remaining', 7, 'waitlist_enabled', true), true),
  ((SELECT id FROM structures WHERE name = 'Centre Équestre des Côteaux'), 'Stage Équitation Vacances', 'Vacances', 'Stage équitation tous niveaux. Soins chevaux, voltige, balade forêt.', ARRAY['https://images.unsplash.com/photo-1553284965-83fd3e82fa5a?w=800'], 7, 15, ARRAY['équitation', 'chevaux', 'nature'], 200, 'Bombe fournie', '["CAF", "PassSport"]'::jsonb, true, true, jsonb_build_object('pmr_access', true, 'adapted_equipment', true, 'specialized_staff', true), jsonb_build_object('seats_total', 12, 'seats_remaining', 5, 'waitlist_enabled', true), true),
  ((SELECT id FROM structures WHERE name = 'Colonie Le Grand Air - Pilat'), 'Camp Aventure Été', 'Vacances', 'Séjour nature Pilat: randonnée, escalade, bivouac. 1 semaine aventure.', ARRAY['https://images.unsplash.com/photo-1478131143081-80f7f84ca84d?w=800'], 11, 16, ARRAY['aventure', 'nature', 'camping', 'été'], 380, '7 jours pension complète', '["CAF", "PassSport"]'::jsonb, true, true, jsonb_build_object('pmr_access', false), jsonb_build_object('seats_total', 20, 'seats_remaining', 8, 'waitlist_enabled', true), true),
  ((SELECT id FROM structures WHERE name = 'Centre Aéré Les Petits Loups'), 'Centre Aéré Vacances Petites', 'Vacances', 'Centre aéré petites vacances: activités variées, sorties. 1 ou 2 semaines.', ARRAY['https://images.unsplash.com/photo-1517164850305-99a3e65bb47e?w=800'], 6, 12, ARRAY['centre aéré', 'vacances', 'loisirs'], 180, 'Semaine complète repas inclus', '["CAF"]'::jsonb, true, false, jsonb_build_object('pmr_access', true, 'adapted_equipment', true, 'specialized_staff', true), jsonb_build_object('seats_total', 50, 'seats_remaining', 28, 'waitlist_enabled', true), true),
  ((SELECT id FROM structures WHERE name = 'Base de Loisirs du Barrage de Grangent'), 'Canoë-Kayak Été', 'Vacances', 'Stage canoë-kayak lac Grangent. Pagaie, sécurité, descente rivière.', ARRAY['https://images.unsplash.com/photo-1502680390469-be75c86b636f?w=800'], 10, 17, ARRAY['canoë', 'kayak', 'nautique', 'été'], 160, 'Matériel fourni', '["CAF", "PassSport"]'::jsonb, true, true, jsonb_build_object('pmr_access', false), jsonb_build_object('seats_total', 14, 'seats_remaining', 6, 'waitlist_enabled', true), true);